name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update version and Retag
        run: |
          # 1. Извлекаем версию
          RAW_VERSION=${GITHUB_REF_NAME#v}
          VERSION=$(echo "$RAW_VERSION" | tr -d '[:space:]')
          echo "Чистая версия: $VERSION"
          
          # 2. ищем manifest.json в папке custom_components
          FILE=$(find custom_components -name "manifest.json" | head -n 1)
          
          if [ -z "$FILE" ]; then
            echo "Ошибка: manifest.json не найден!"
            exit 1
          fi
          echo "Найден файл по пути: $FILE"
          
          # 3. Прицельная замена
          sed -i "s|\"version\":\s*\"[^\"]*\"|\"version\": \"$VERSION\"|g" "$FILE"
          
          # 4. Проверка результата
          grep '"version":' "$FILE"

          # 5. Git config
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 6. Фиксация (используем найденную переменную $FILE)
          git add "$FILE"
          
          if git diff --staged --quiet; then
            echo "Изменений нет."
          else
            # Добавляем [skip ci], чтобы не мучить GitHub лишними проверками
            git commit -m "chore: bump version to $VERSION [skip ci]"
            git push origin HEAD:main
            
            # Переставляем тег
            git tag -f ${{ github.ref_name }}
            git push -f origin ${{ github.ref_name }}
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
